# run: conda env create --file environment.yml
name: het_attention_tsp
channels:
- pytorch
dependencies:
- python=3.8
- anaconda=2024
- tqdm
- pytorch=2.2
- torchvision=0.17
- cuda91=1.0
- pip:
  - tensorboard_logger=0.1